#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
PROG=/usr/sbin/sesamed

start_service () {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

stop_service () {
	rm /tmp/sesame_was_here
}
